version: '3'
services:
  moc_chat:
    image: alexeyzh/moc_chat:1.0.0
    ports:
      - 8090:8090
      - 1030:8090
    environment:
      - DB_URL=jdbc:postgresql://database:5432/chat
      - DIALOGFLOW_CLIENT_EMAIL=chat-bot-client@moc-chat-hubdau.iam.gserviceaccount.com
      - DIALOGFLOW_PROJECT_ID=moc-chat-hubdau
      - DIALOGFLOW_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtApanEZedB+Gk\npixc5loVJ4Vm+3HhigvblLGDRUQjdvjAwZrtJCB/WZF+qde5TnKDLXKq576E6JWa\nc0VeyxGGjYHVJ3BcVnvMVE+/K7MEJCeIq9Gpn8Eqw5rbxAQOf2nnJ0wH01STF0f1\ncK/Qa3sJjzTq/pd4IPm5E6zG2V/1T4Ch+iAX7rXI4JQ4D5w7ZL2nPVaDvfTjoR5T\nFbNn0xENSgNP0cjNsSW0ObIkGh6rU5IkNMAq+dyxygNRwq3ozz+L4eVGe8URn0gn\nRsGz1j9HvQ8yxd13QeBV5olrqg1HhILL/bpkNeBspGEyoaLr/pKXwUQLV14/99vO\nV93NStdZAgMBAAECggEAJy4KYvxbat7hjTFqo4ExDlBcaBVyVUK3a7sxNgqmIyfq\nrnBJvwFq8JwelGIvLdJjoWxV5vlDToMDei43m/990QxTxis/yVF2iK/hPWhOipYL\nc+qBORoqGx6f/7vUtVnKaGQgVjdYFFV14NHrptXoT6JkOAF+2OAS3YRkoMWScxF2\nNZiCIGYuYI/4ZgCx+Ebjbq2G5BD4/XLnIU0bj20Duk0MN0fOfxXCHGdDw4A/YE1p\n+eiJ0PqMbdclWjuNHQ7dVVd2/747VVHFBdFjZynVT21Piu//KNjymSgkuF6el/ef\nnFstBfc18bHi0SefSFpsXFNcDvUx8RuTpdJUIv+nrwKBgQDXjB8oGGl9wObJscVT\nWiKj/UZaLFXqd+mHiD825SVOEvXDm4Zipqc8iDv/Cj2OWjpv2zQE7Xu39iZDVCZ7\nM7BRo8F3n2uZwL9pbMcNnO5ybWejGV0GnYJcUN4W7rjdomxVfBvDifekdEvPkMyi\npVMrUE4Czyp+spxpWvtEEmrtbwKBgQDNesihGYAmy5cB1W9uRHfGetUxoWF8MjGd\nf6d+eexzQahEob4vll4XQhkAdThoZK3o5qqcvDSqJZBksbU4ZdPuzwqlS0cSPC7A\nipdqvM02IJG5nJZDPKbQ8ICqb0rYwH2Zb/O9ymVbPEQ9pXsyEvrFTHl3aJHVPZ+r\nujq3OFIztwKBgHNtvmGicRu+6dipMprochSP1dUEWR4vCQhjlja3j7q3vJT7/INn\n67cm3bo+qahJ+XFdWgYph0+Eqgj0T4c6rvmJUFnXLbAw4FB8yDwqBieRHybgtkiM\noPr+83Akdyt5h7pftB6LC+stvEtzp6KSFm/jmWM3vfILhGeHKXfSxSBRAoGBALR5\ntaIZ3b81bkrEBn1ZUcJYvMw8rH0DMSTerGSf/hg1gO/XCE6PydCv03nde0/lrgI0\nJ4JGpBMVrz9h/oOsnHrSCs2n0qKnjYC7ucacUbnK3XOjny8rJHG766bG3XyHhUmx\nVOpLzL5XrrBemlge53dHdiB1DjG3UHjqtwuaQkj9AoGAM3OvWa8ebe5DB5d/nWK9\nrWTuzrP7EJx1j9jcwJObskHLAi9qdXpSUCndbfnsdkRS8qIOlmo/ng5afgwe1IQq\nkYRdlb1OV8quJqKBcinR2sD7V+M4QPUd+0sSN7csWh8wQWBqovB03mZypNx3ppgh\ng3UpHQbI02rmeQ67XI1KQL8=\n-----END PRIVATE KEY-----\n
    links:
      - "dbchat:database"
    networks:
      - common
  dbchat:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: chat
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - common
networks:
  common:

volumes:
  chatvolume:
