version: '3'
services:
  dbchat:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: chat
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - common
networks:
  common:

volumes:
  chatvolume:
