server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/moc_chat.p12
    key-alias: ${SSL_KEY_ALIAS:moc_chat}
    key-store-password: ${SSL_KEY_STORE_PASS:moc_chat}

security:
  require-ssl: true